# Site settings
title: OuiShare Labs
email: labs@ouishare.net
description: > # this means to ignore newlines until "baseurl:"
  Connecting actors in the Open Web
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ouisharelabs
github_username:  ouisharelabs

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-redirect-from

# Content types
collections:
  projects:
    output: true
  events:
    output: true

#Default settings by content types
defaults: 
  posts:
    layout: post
  projects:
    layout: project