# Site settings
title: OuiShare Labs
email: labs@ouishare.net
description: > # this means to ignore newlines until "baseurl:"
  Connecting actors in the Open Web
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://labs.ouishare.net" # the base hostname & protocol for your site
twitter_username: ouisharelabs
github_username:  ouisharelabs

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-redirect-from

# Content types
collections:
  projects:
    output: true
  events:
    output: true
  webmentions:
    output: true

#Default settings by content types
defaults: 
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
  - 
    scope:
      path: "projects"
      type: "projects"
    values:
      layout: project
  - 
    scope:
      path: "events"
      type: "events"
    values:
      layout: event
